# This is a basic workflow to help you get started with Actions

name: CI
env:
        zhanghao: ${{ secrets.zhanghao }}
        mima: ${{ secrets.mima }}
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
     # - name: Run a one-line script
        

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          ls
          mkdir test
          cd test
          # git clone https://github.com/ubun222/Bash-Enlish-Training.git
          # cd ./Bash-Enlish-Training
          echo ${{ secrets.zhanghao }}
          echo 0
          pwd
          git init 
          git config --global credential.helper store
          git config --global user.name 'ubun222'
          git config --global user.email 925966086@qq.com
          git remote add origin https://${{ secrets.zhanghao }}:${{ secrets.mima }}@github.com/ubun222/Bash-Enlish-Training.git
          git pull https://github.com/ubun222/Bash-Enlish-Training ubun222-patch-3
          #cat ./allinone.txt
          rm ./allinone.txt
          ./txts.sh | ./allinone.sh
          echo $(date) > date.txt
          git add date.txt
          git add allinone.txt
          git commit -m "update allinone.txt and date"
          git push origin HEAD:ubun222-patch-3
          
          
